In [1]:
import math
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
max_len = 5000
d_model = 100
pe = torch.zeros(max_len, d_model)
print(pe.size())
print(pe)

torch.Size([5000, 100])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


In [3]:
position = torch.arange(0, max_len, dtype=torch.float)
print(position.size())
print(position)
position = position.unsqueeze(1)
print(position.size())
print(position)

torch.Size([5000])
tensor([0.0000e+00, 1.0000e+00, 2.0000e+00,  ..., 4.9970e+03, 4.9980e+03,
        4.9990e+03])
torch.Size([5000, 1])
tensor([[0.0000e+00],
        [1.0000e+00],
        [2.0000e+00],
        ...,
        [4.9970e+03],
        [4.9980e+03],
        [4.9990e+03]])


In [4]:
div_term = torch.arange(0, d_model, 2).float() / d_model
print(div_term.size())
print(div_term)
div_term = div_term * (-math.log(10000.0))
print(div_term.size())
print(div_term)
div_term = torch.exp(div_term)
print(div_term.size())
print(div_term)

torch.Size([50])
tensor([0.0000, 0.0200, 0.0400, 0.0600, 0.0800, 0.1000, 0.1200, 0.1400, 0.1600,
        0.1800, 0.2000, 0.2200, 0.2400, 0.2600, 0.2800, 0.3000, 0.3200, 0.3400,
        0.3600, 0.3800, 0.4000, 0.4200, 0.4400, 0.4600, 0.4800, 0.5000, 0.5200,
        0.5400, 0.5600, 0.5800, 0.6000, 0.6200, 0.6400, 0.6600, 0.6800, 0.7000,
        0.7200, 0.7400, 0.7600, 0.7800, 0.8000, 0.8200, 0.8400, 0.8600, 0.8800,
        0.9000, 0.9200, 0.9400, 0.9600, 0.9800])
torch.Size([50])
tensor([-0.0000, -0.1842, -0.3684, -0.5526, -0.7368, -0.9210, -1.1052, -1.2894,
        -1.4737, -1.6579, -1.8421, -2.0263, -2.2105, -2.3947, -2.5789, -2.7631,
        -2.9473, -3.1315, -3.3157, -3.4999, -3.6841, -3.8683, -4.0525, -4.2368,
        -4.4210, -4.6052, -4.7894, -4.9736, -5.1578, -5.3420, -5.5262, -5.7104,
        -5.8946, -6.0788, -6.2630, -6.4472, -6.6314, -6.8157, -6.9999, -7.1841,
        -7.3683, -7.5525, -7.7367, -7.9209, -8.1051, -8.2893, -8.4735, -8.6577,
        -8.8419, -9.0261])
torch.Size

In [5]:
print(position.size())
print(div_term.size())
print((position * div_term).size())

torch.Size([5000, 1])
torch.Size([50])
torch.Size([5000, 50])


In [6]:
pe = pe.unsqueeze(0).transpose(0, 1)
print(pe.size())

torch.Size([5000, 1, 100])


In [7]:
x = torch.zeros(max_len, 128, d_model)
print(x.size())
x = x + pe[:x.size(0), :]
print(x.size())

torch.Size([5000, 128, 100])
torch.Size([5000, 128, 100])


In [8]:
sz = 10
mask = torch.ones(sz,sz)
print(mask)
mask = torch.tril(mask)
print(mask)
mask = torch.log(mask)
print(mask)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]

In [5]:
why_not_fast_path = "abc"
if not why_not_fast_path:
    print("One")

In [17]:
import torch
t = torch.zeros(3, 4, 5)
print(t.size())
a, b, c = torch.chunk(t, 3, dim=0)
print(a.size())

torch.Size([3, 4, 5])
torch.Size([1, 4, 5])


In [19]:
a = torch.rand(3, 4, 5)
a.transpose(0, 1).view(20, 3)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [20]:
a.transpose(0, 1).reshape(20, 3)

tensor([[0.4536, 0.1439, 0.4902],
        [0.7070, 0.2201, 0.4560],
        [0.7095, 0.0484, 0.5964],
        [0.6026, 0.6514, 0.8462],
        [0.3512, 0.9491, 0.0237],
        [0.9265, 0.0818, 0.7054],
        [0.5664, 0.2713, 0.5917],
        [0.8704, 0.1799, 0.6283],
        [0.6517, 0.4384, 0.6334],
        [0.3369, 0.8768, 0.5718],
        [0.7397, 0.0415, 0.7496],
        [0.9603, 0.3549, 0.5909],
        [0.8220, 0.6783, 0.9836],
        [0.2580, 0.6975, 0.6759],
        [0.1229, 0.9863, 0.1275],
        [0.8709, 0.3167, 0.5224],
        [0.4570, 0.0820, 0.4466],
        [0.1001, 0.2881, 0.1149],
        [0.6790, 0.6664, 0.4065],
        [0.4172, 0.3655, 0.1776]])